### ISSUE TITLE
Make this webapp work with a PIN

### ISSUE THREAD

**Issue by rqbanerjee** [nestlabs/rest-streaming#5]
Hi,
I'm trying to run this webapp on a local box. Nest.com gives me a pin but no where on the webapp to input the PIN.
- go to http://localhost:3000/ 
- "API Connection: 0" . Click "SIGN IN TO NEST"
- home.nest.com asks for approval 

" Works with Nest -- raj enterprises would like to do the following: " . Click 'accept'

- Get: 
'''
   Pincode
   Use this pincode to connect with Nest.
   BKX11111111
- Where do I put the PIN? Nothing in the README or findable in the docs to input the PIN.

**Comment by ryanseys** [comment]
We don't use the PIN to authenticate, we use standard OAuth 2.0. 

Here's a guide: https://developer.nest.com/documentation/cloud/authorization-reference

**Comment by Fchaubard** [comment]
Then why does your demo code show a PIN?
