### ISSUE TITLE
Nest requires redirect URI to be https

### ISSUE THREAD

**Issue by Vandalko** [nestlabs/rest-streaming#8]
Doc states:
> Set your client redirect URI to be http://localhost:3000/auth/nest/callback

But https://developer.nest.com/products/product-id/edit accepts only **https** links as **Redirect URI**

**Comment by beriberikix** [comment]
Thanks for reporting Olexandr. We're investigating the issues and will update this issue when I know more.

To unblock your development can you use a local/self-signed cert?

**Comment by ryanseys** [comment]
This used to be an issue and it was fixed so that http could be set for localhost. Unless the issue was reintroduced. @aurman will know more.

@Vandalko Did you try with localhost? Or maybe 127.0.0.1 ?

**Comment by Vandalko** [comment]
@ryanseys you are correct it accepts **localhost** with **http** link.
Ok, thx, I understand your hack :)

**Comment by Vandalko** [comment]
@ryanseys quick question - does self-signed certificates work in case of non-localhost ? Or Nest requires verified signature ?

**Comment by liorgulescu** [comment]
http://localhost:3000/auth/nest/callback works as a redirect URI. The rule is either HTTPS or localhost.

**Comment by ryanseys** [comment]
@Vandalko I'm not sure, but for production applications it usually makes sense to not use a self-signed certificate. Especially now that you can get a free certificate from https://letsencrypt.org/

**Comment by beriberikix** [comment]
Nice protip @ryanseys!
